# Generated by Django 4.2.29 on 2026-03-19 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('role', models.CharField(max_length=100, verbose_name='Role')),
                ('vacancy_link', models.URLField(verbose_name='Vacancy Link')),
                ('vacancy_description', models.TextField(verbose_name='Vacancy Description')),
                ('company_address', models.CharField(blank=True, null=True, verbose_name='Company Address')),
                ('contract_type', models.CharField(blank=True, choices=[('PJ', 'PJ'), ('CLT', 'CLT'), ('FREELANCE', 'Freelance')], max_length=20, null=True, verbose_name='Contract Type')),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('GHOSTED', 'Ghosted'), ('REJECTED', 'Rejected'), ('IN PROCESS', 'In Process'), ('OFFERED', 'Offered'), ('ACCEPTED', 'Accepted')], default='APPLIED', max_length=20, verbose_name='Status')),
                ('date_applied', models.DateField(verbose_name='Date Applied')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('salary_min', models.IntegerField(blank=True, null=True, verbose_name='Minimum Salary')),
                ('salary_max', models.IntegerField(blank=True, null=True, verbose_name='Maximum Salary')),
                ('salary_period', models.CharField(blank=True, choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly'), ('HOURLY', 'Hourly')], max_length=10, null=True, verbose_name='Salary Period')),
                ('currency', models.CharField(blank=True, choices=[('BRL', 'BRL'), ('USD', 'USD'), ('EUR', 'EUR')], max_length=5, null=True, verbose_name='Currency')),
                ('work_mode', models.CharField(blank=True, choices=[('REMOTE', 'Remote'), ('HYBRID', 'Hybrid'), ('ON-SITE', 'On-Site')], max_length=10, null=True, verbose_name='Work Mode')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('RECRUITER CONTACT', 'Recruiter Contact'), ('INTERVIEW', 'Interview'), ('TECHNICAL INTERVIEW', 'Technical Interview'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted')], max_length=30, verbose_name='Event Type')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('event_date', models.DateField(verbose_name='Event Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='job_applications.application')),
            ],
        ),
    ]
