# Generated by Django 6.0.3 on 2026-03-16 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('RECRUITER CONTACT', 'Recruiter Contact'), ('INTERVIEW', 'Interview'), ('TECHNICAL INTERVIEW', 'Technical Interview'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted')], max_length=30, verbose_name='Event Type')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('event_date', models.DateField(verbose_name='Event Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='job_applications.application')),
            ],
        ),
    ]
